# Generated by Django 4.2.17 on 2024-12-19 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("type", models.CharField(max_length=50)),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Common"),
                            ("rare", "Rare"),
                            ("legendary", "Legendary"),
                        ],
                        max_length=50,
                    ),
                ),
                ("icon", models.URLField(blank=True, null=True)),
                ("stat_modifiers", models.JSONField(blank=True, null=True)),
                ("effect", models.TextField(blank=True, null=True)),
                ("durability", models.IntegerField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "sub_category",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("stack_size", models.IntegerField(default=1)),
                ("cooldown", models.IntegerField(default=0)),
                ("upgrade_level", models.IntegerField(default=0)),
                ("drop_rate", models.FloatField(default=0.0)),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
                "ordering": ["name"],
            },
        ),
    ]
